version: '3.8'

services:
  bookstack:
    image: solidnerd/bookstack:latest
    container_name: bookstack
    restart: unless-stopped
    environment:
      - APP_URL=${APP_URL}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_KEY=${APP_KEY}
    #ports:
    #  - "8080:80"
    volumes:
      - data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: bookstack_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql

volumes:
  data:
  db:

