services:
  # ... define other services using the `data` volume here
  backup:
    image: offen/docker-volume-backup:latest
    environment:
      SSH_HOST_NAME: 192.168.1.1
      SSH_PORT: 9006
      SSH_USER: backupssh
      SSH_REMOTE_PATH: /home/backupssh
    volumes:
      - /var/lib/docker/volumes/:/backup/my-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/synack/sshkeys/backupssh.key:/root/.ssh/id_rsa
      - /etc/localtime:/etc/localtime:ro #Match time zones with the host machine
