version: "3.8"

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.22.27
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
      - ./pocketbase/pb_hooks:/pb_hooks
    networks:
      - app_network
    environment:
      - ORIGIN=http://localhost:3000 # Allow CORS requests from SvelteKit during development

  sveltekit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sveltekit-app
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
    env_file:
      - .env
    environment:
      - PUBLIC_POCKETBASE_URL=http://pocketbase:8090 # Use Docker network service name
      - PUBLIC_APPLICATION_NAME=${PUBLIC_APPLICATION_NAME}
      - PUBLIC_APPLICATION_URL=${PUBLIC_APPLICATION_URL}
      - ENCRYPTION=${ENCRYPTION}
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
      - METADATA_SCRAPER_URL=${METADATA_SCRAPER_URL}
      - HASH_ALGORITHM=${HASH_ALGORITHM}
      - HASH_KEY=${HASH_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PRO_PRICE_ID=${STRIPE_PRO_PRICE_ID}
      - STRIPE_ENTERPRISE_PRICE_ID=${STRIPE_ENTERPRISE_PRICE_ID}
      - PUBLIC_SITE_URL=${PUBLIC_SITE_URL}
      - STRIPE_PRODUCT_ID=${STRIPE_PRODUCT_ID}
      - ORIGIN=http://localhost:3000
    networks:
      - app_network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app_network:
    driver: bridge
